# Generated by Django 2.2.2 on 2019-07-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido_p', models.CharField(max_length=40)),
                ('Apellido_m', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.BigIntegerField(max_length=14)),
                ('mensaje', models.TextField(max_length=2000)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='Ciudad_p',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Color_pelo_p',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Genero_p',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Nombre_p',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Ojos_p',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Pais_p',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Piel_p',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Tipo_pelo_p',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(max_length=14),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_compra', models.DateField(blank=True, null=True)),
                ('Num_cuentos', models.IntegerField(max_length=6)),
                ('Venta_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IP', models.CharField(max_length=1)),
                ('Id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuento.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Contenido', models.TextField(max_length=200000)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ventas', models.ManyToManyField(to='cuento.Ventas')),
            ],
        ),
    ]
