# Generated by Django 2.2.2 on 2019-07-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuento', '0003_auto_20190706_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuento',
            name='ventas',
        ),
        migrations.AddField(
            model_name='ventas',
            name='cuento',
            field=models.ManyToManyField(to='cuento.Cuento'),
        ),
    ]
