# Generated by Django 2.2.2 on 2019-07-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuento', '0004_auto_20190706_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Gafas_p',
            field=models.BooleanField(null=True),
        ),
    ]
