# Generated by Django 2.2.2 on 2019-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuento', '0005_cliente_gafas_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='IP',
            field=models.BooleanField(null=True),
        ),
    ]
